---
title: "Spatial (Granger) Causality Test (SCT)"
author: "Wenbo Lv"
date: "2025-05-01"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{SCT}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



## Model principles

Let us begin by defining two spatial cross-sectional series $\{x_s\}_{s \in S}$ and $\{y_s\}_{s \in S}$, where $S$ represents the study area.

We use:

$$
\mathcal{X}_W = \{ W_i x \mid W_i \in \mathcal{W}(x, y) \}
$$

$$
\mathcal{Y}_W = \{ W_i y \mid W_i \in \mathcal{W}(x, y) \}
$$

to denote the sets of spatial lags of $x$ and $y$ given by all the weighting matrices in $\mathcal{W}(x, y)$(that is the set of spatial
dependence structures between $x$ and $y$).
 

We say that $\{x_s\}_{s \in S}$ does not cause $\{y_s\}_{s \in S}$ **under the spatial structures** $\mathcal{X}_W$ and $\mathcal{Y}_W$ if

$$
h_{y |\mathcal{Y}_W}(m) = h_{y | \mathcal{Y}_W,\mathcal{X}_W}(m)
$$
A unilateral non-parametric test can be applied to assess the spatial causality via the following null hypothesis:

$$
H_0 : \{x_s\}_{s \in S} \text{ does not cause } \{y_s\}_{s \in S} \text{ under the spatial structures } \mathcal{X}_W \text{ and } \mathcal{Y}_W, $$

with the following statistic:

$$
\hat{\delta}(\mathcal{Y}_W, \mathcal{X}_W) = \hat{h}_{y |\mathcal{Y}_W}(m) - \hat{h}_{y | \mathcal{Y}_W,\mathcal{X}_W}(m)
$$

where $\hat{h}_*(m)$ is the estimated conditional symbolic entropy using Shannon’s entropy with $m-1$ nearest neighbors. The alternative is that the null hypothesis of is not true.

If $\mathcal{X}_W$ does not contain extra information about $y$ then $\hat{\delta}(\mathcal{Y}_W, \mathcal{X}_W) = 0$, otherwise, $ \hat{\delta}(\mathcal{Y}_W, \mathcal{X}_W) > 0$. 

$h_{y |\mathcal{Y}_W}(m)$ measures the uncertainty of the distribution of symbols of $y$, conditional to the symbols of its spatial lag, $ \mathcal{Y}_W$. Moreover, $h_{y | \mathcal{Y}_W,\mathcal{X}_W}(m)$ measures the uncertainty of the distribution of symbols of $y$, conditional to the symbols of the spatial lags of $y$, $\mathcal{Y}_W$, and of $x$, $ \mathcal{X}_W$. If the second variable, $x$, indeed causes the first one then there should be a significant decrease in the entropy, and the statistic $\hat{\delta}(\mathcal{Y}_W, \mathcal{X}_W)$ will take on high positive values. If there is only a spatial correlation, but not causation, the difference between both entropies will be small. The statistical significance of $\hat{\delta}(\mathcal{Y}_W, \mathcal{X}_W)$ is assessed using spatial block bootstrap.

## Usage examples

### An example of spatial lattice data

Load the `spEDM` package and the columbus OH dataset:


``` r
library(spEDM)

columbus = sf::read_sf(system.file("case/columbus.gpkg", package="spEDM"))
columbus
## Simple feature collection with 49 features and 6 fields
## Geometry type: POLYGON
## Dimension:     XY
## Bounding box:  xmin: 5.874907 ymin: 10.78863 xmax: 11.28742 ymax: 14.74245
## Projected CRS: Undefined Cartesian SRS with unknown unit
## # A tibble: 49 × 7
##    hoval   inc  crime  open plumb discbd                                 geom
##    <dbl> <dbl>  <dbl> <dbl> <dbl>  <dbl>                            <POLYGON>
##  1  80.5 19.5  15.7   2.85  0.217   5.03 ((8.624129 14.23698, 8.5597 14.7424…
##  2  44.6 21.2  18.8   5.30  0.321   4.27 ((8.25279 14.23694, 8.282758 14.229…
##  3  26.4 16.0  30.6   4.53  0.374   3.89 ((8.653305 14.00809, 8.81814 14.002…
##  4  33.2  4.48 32.4   0.394 1.19    3.7  ((8.459499 13.82035, 8.473408 13.83…
##  5  23.2 11.3  50.7   0.406 0.625   2.83 ((8.685274 13.63952, 8.677577 13.72…
##  6  28.8 16.0  26.1   0.563 0.254   3.78 ((9.401384 13.5504, 9.434411 13.694…
##  7  75    8.44  0.178 0     2.40    2.74 ((8.037741 13.60752, 8.062716 13.60…
##  8  37.1 11.3  38.4   3.48  2.74    2.89 ((8.247527 13.58651, 8.2795 13.5965…
##  9  52.6 17.6  30.5   0.527 0.891   3.17 ((9.333297 13.27242, 9.671007 13.27…
## 10  96.4 13.6  34.0   1.55  0.558   4.33 ((10.08251 13.03377, 10.0925 13.052…
## # ℹ 39 more rows
```

Use SCT to detect spatial causality among the variables *inc*, *crime*, and *hoval* :


``` r
# house value and crime
sc.test(columbus, "hoval", "crime", k = 15)
## spatial (granger) causality test
## hoval -> crime: statistic = 1.101, p value = 0.526
## crime -> hoval: statistic = 1.484, p value = 0.023

# household income and crime
sc.test(columbus, "inc", "crime", k = 15)
## spatial (granger) causality test
## inc -> crime: statistic = 1.116, p value = 0.449
## crime -> inc: statistic = 0.848, p value = 0.845

# household income and house value
sc.test(columbus, "inc", "hoval", k = 15)
## spatial (granger) causality test
## inc -> hoval: statistic = 1.517, p value = 0.035
## hoval -> inc: statistic = 0.851, p value = 0.922
```

### An example of spatial grid data

Load the `spEDM` package and its soil pollution data:


``` r
library(spEDM)

cu = terra::rast(system.file("case/cu.tif", package="spEDM"))
cu
## class       : SpatRaster 
## dimensions  : 131, 125, 3  (nrow, ncol, nlyr)
## resolution  : 5000, 5000  (x, y)
## extent      : 360000, 985000, 1555000, 2210000  (xmin, xmax, ymin, ymax)
## coord. ref. : North_American_1983_Albers 
## source      : cu.tif 
## names       :         cu, industry, ntl 
## min values  :   1.201607,    0.000,   0 
## max values  : 319.599274,    0.615,  63
```

Use SCT to detect spatial causality among the variables *cu*, *ntl*, and *industry* :


``` r
# nightlight and soil Cu concentration
sc.test(cu, "ntl", "cu", k = 30)
## spatial (granger) causality test
## ntl -> cu: statistic = -1.489, p value = 0
## cu -> ntl: statistic = -3.106, p value = 0

# the density of industrial pollutants and soil Cu concentration
sc.test(cu, "industry", "cu", k = 30)
## spatial (granger) causality test
## industry -> cu: statistic = -1.489, p value = 0
## cu -> industry: statistic = -1.328, p value = 0

# nightlight and the density of industrial pollutants
sc.test(cu, "ntl", "industry", k = 30)
## spatial (granger) causality test
## ntl -> industry: statistic = -1.327, p value = 0
## industry -> ntl: statistic = -3.105, p value = 0
```
