---
title: "Introduction to the spEDM package"
author: "Wenbo Lv"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{spEDM}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "##",
  fig.path = "man/figures/pkgintro/"
)
```

## Overview

The *spEDM* package is an open-source, computationally efficient toolkit designed to provide a unified API for **Spatial Empirical Dynamic Modeling**. It supports a suite of prediction-based causal inference algorithms, including *spatial granger causality tests*, *spatial state-space reconstruction*, and *geographically convergent cross mapping*.  

To facilitate learning and application, *spEDM* includes three typical spatial cross-sectional datasets along with illustrative use cases for each of the core algorithms.

## Installation

Install the stable version from [CRAN](https://CRAN.R-project.org/package=spEDM) with:

```r
install.packages("spEDM", dep = TRUE)
```

Alternatively, you can install the development version from [R-universe](https://stscl.r-universe.dev/spEDM) with:

```r
install.packages("spEDM",
                 repos = c("https://stscl.r-universe.dev",
                           "https://cloud.r-project.org"),
                 dep = TRUE)
```

## Data

## Usage

Users can refer to several additional vignettes for more detailed examples of using *spEDM*, namely:

| *Model* | *Vignette* |
|---------------------|--------------------|
| State Space Reconstruction |[SSR](https://stscl.github.io/spEDM/articles/SSR.html)|
| Spatial (Granger) Causality Test |[SCT](https://stscl.github.io/spEDM/articles/SCT.html)|
| Geographical Convergent Cross Mapping |[GCCM](https://stscl.github.io/spEDM/articles/GCCM.html)|

## References

Herrera, M., Mur, J., & Ruiz, M. (2016). Detecting causal relationships between spatial processes. Papers in Regional Science, 95(3), 577–595. https://doi.org/10.1111/pirs.12144

Gao, B., Yang, J., Chen, Z., Sugihara, G., Li, M., Stein, A., Kwan, M.-P., & Wang, J. (2023). Causal inference from cross-sectional earth system data with geographical convergent cross mapping. Nature Communications, 14(1). https://doi.org/10.1038/s41467-023-41619-6
