// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppThread.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// CppMean
double CppMean(const std::vector<double>& vec, bool NA_rm);
RcppExport SEXP _spEDM_CppMean(SEXP vecSEXP, SEXP NA_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<double>& >::type vec(vecSEXP);
    Rcpp::traits::input_parameter< bool >::type NA_rm(NA_rmSEXP);
    rcpp_result_gen = Rcpp::wrap(CppMean(vec, NA_rm));
    return rcpp_result_gen;
END_RCPP
}
// CppVariance
double CppVariance(const std::vector<double>& vec, bool NA_rm);
RcppExport SEXP _spEDM_CppVariance(SEXP vecSEXP, SEXP NA_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<double>& >::type vec(vecSEXP);
    Rcpp::traits::input_parameter< bool >::type NA_rm(NA_rmSEXP);
    rcpp_result_gen = Rcpp::wrap(CppVariance(vec, NA_rm));
    return rcpp_result_gen;
END_RCPP
}
// CppCovariance
double CppCovariance(const std::vector<double>& vec1, const std::vector<double>& vec2, bool NA_rm);
RcppExport SEXP _spEDM_CppCovariance(SEXP vec1SEXP, SEXP vec2SEXP, SEXP NA_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<double>& >::type vec1(vec1SEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type vec2(vec2SEXP);
    Rcpp::traits::input_parameter< bool >::type NA_rm(NA_rmSEXP);
    rcpp_result_gen = Rcpp::wrap(CppCovariance(vec1, vec2, NA_rm));
    return rcpp_result_gen;
END_RCPP
}
// PearsonCor
double PearsonCor(const std::vector<double>& y, const std::vector<double>& y_hat, bool NA_rm);
RcppExport SEXP _spEDM_PearsonCor(SEXP ySEXP, SEXP y_hatSEXP, SEXP NA_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<double>& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type y_hat(y_hatSEXP);
    Rcpp::traits::input_parameter< bool >::type NA_rm(NA_rmSEXP);
    rcpp_result_gen = Rcpp::wrap(PearsonCor(y, y_hat, NA_rm));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_spEDM_CppMean", (DL_FUNC) &_spEDM_CppMean, 2},
    {"_spEDM_CppVariance", (DL_FUNC) &_spEDM_CppVariance, 2},
    {"_spEDM_CppCovariance", (DL_FUNC) &_spEDM_CppCovariance, 3},
    {"_spEDM_PearsonCor", (DL_FUNC) &_spEDM_PearsonCor, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_spEDM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
