# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RcppLaggedIndices <- function(vec, nbmat, lagNum) {
    .Call(`_spEDM_RcppLaggedIndices`, vec, nbmat, lagNum)
}

RcppGenEmbeddings <- function(vec, nbmat, E) {
    .Call(`_spEDM_RcppGenEmbeddings`, vec, nbmat, E)
}

RcppDist <- function(matrix) {
    .Call(`_spEDM_RcppDist`, matrix)
}

RcppClosestIndices <- function(distmat, libsize) {
    .Call(`_spEDM_RcppClosestIndices`, distmat, libsize)
}

RcppCCMWeight <- function(distmat, closestIndices, libsize) {
    .Call(`_spEDM_RcppCCMWeight`, distmat, closestIndices, libsize)
}

RcppSimplexProjection <- function(y, x, nbmat, libsize, E) {
    .Call(`_spEDM_RcppSimplexProjection`, y, x, nbmat, libsize, E)
}

