# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RcppLaggedVar4Grid <- function(mat, lagNum) {
    .Call(`_spEDM_RcppLaggedVar4Grid`, mat, lagNum)
}

RcppGenGridEmbeddings <- function(mat, E, includeself) {
    .Call(`_spEDM_RcppGenGridEmbeddings`, mat, E, includeself)
}

RcppLocateGridIndices <- function(curRow, curCol, totalRow, totalCol) {
    .Call(`_spEDM_RcppLocateGridIndices`, curRow, curCol, totalRow, totalCol)
}

RcppSimplex4Grid <- function(mat, lib, pred, E, b, threads) {
    .Call(`_spEDM_RcppSimplex4Grid`, mat, lib, pred, E, b, threads)
}

RcppGCCM4Grid <- function(xMatrix, yMatrix, lib_sizes, pred, E, tau, b, simplex, theta, threads, progressbar) {
    .Call(`_spEDM_RcppGCCM4Grid`, xMatrix, yMatrix, lib_sizes, pred, E, tau, b, simplex, theta, threads, progressbar)
}

DetectMaxNumThreads <- function() {
    .Call(`_spEDM_DetectMaxNumThreads`)
}

RcppLaggedVar4Lattice <- function(nb, lagNum) {
    .Call(`_spEDM_RcppLaggedVar4Lattice`, nb, lagNum)
}

RcppGenLatticeEmbeddings <- function(vec, nb, E, includeself) {
    .Call(`_spEDM_RcppGenLatticeEmbeddings`, vec, nb, E, includeself)
}

RcppSimplex4Lattice <- function(x, nb, lib, pred, E, b, threads) {
    .Call(`_spEDM_RcppSimplex4Lattice`, x, nb, lib, pred, E, b, threads)
}

RcppGCCM4Lattice <- function(x, y, nb, libsizes, E, tau, b, simplex, theta, threads, progressbar) {
    .Call(`_spEDM_RcppGCCM4Lattice`, x, y, nb, libsizes, E, tau, b, simplex, theta, threads, progressbar)
}

RcppMean <- function(vec, NA_rm = FALSE) {
    .Call(`_spEDM_RcppMean`, vec, NA_rm)
}

RcppSum <- function(vec, NA_rm = FALSE) {
    .Call(`_spEDM_RcppSum`, vec, NA_rm)
}

RcppVariance <- function(vec, NA_rm = FALSE) {
    .Call(`_spEDM_RcppVariance`, vec, NA_rm)
}

RcppCovariance <- function(vec1, vec2, NA_rm = FALSE) {
    .Call(`_spEDM_RcppCovariance`, vec1, vec2, NA_rm)
}

RcppMAE <- function(vec1, vec2, NA_rm = FALSE) {
    .Call(`_spEDM_RcppMAE`, vec1, vec2, NA_rm)
}

RcppRMSE <- function(vec1, vec2, NA_rm = FALSE) {
    .Call(`_spEDM_RcppRMSE`, vec1, vec2, NA_rm)
}

RcppAbs <- function(vec1, vec2) {
    .Call(`_spEDM_RcppAbs`, vec1, vec2)
}

RcppSumNormalize <- function(vec, NA_rm = FALSE) {
    .Call(`_spEDM_RcppSumNormalize`, vec, NA_rm)
}

RcppPearsonCor <- function(y, y_hat, NA_rm = FALSE) {
    .Call(`_spEDM_RcppPearsonCor`, y, y_hat, NA_rm)
}

RcppConfidence <- function(r, n, level = 0.05) {
    .Call(`_spEDM_RcppConfidence`, r, n, level)
}

RcppLinearTrendRM <- function(vec, xcoord, ycoord, NA_rm = FALSE) {
    .Call(`_spEDM_RcppLinearTrendRM`, vec, xcoord, ycoord, NA_rm)
}

RcppSVD <- function(X) {
    .Call(`_spEDM_RcppSVD`, X)
}

