# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CppMean <- function(vec, NA_rm = FALSE) {
    .Call('_spEDM_CppMean', PACKAGE = 'spEDM', vec, NA_rm)
}

CppVariance <- function(vec, NA_rm = FALSE) {
    .Call('_spEDM_CppVariance', PACKAGE = 'spEDM', vec, NA_rm)
}

CppCovariance <- function(vec1, vec2, NA_rm = FALSE) {
    .Call('_spEDM_CppCovariance', PACKAGE = 'spEDM', vec1, vec2, NA_rm)
}

PearsonCor <- function(y, y_hat, NA_rm = FALSE) {
    .Call('_spEDM_PearsonCor', PACKAGE = 'spEDM', y, y_hat, NA_rm)
}

